### ISSUE TITLE
Make text wrap, or cut it

### ISSUE THREAD

**Issue by OshidaBCF** [Warthunder-Open-Source-Foundation/wt_custom_lang#25]
![image](https://user-images.githubusercontent.com/61458287/174500529-0089a2ba-c4d0-4436-b6e4-76a41411d6f2.png)

I think the problem is easy to understand...

sorry

**Comment by FlareFlo** [comment]
I can remember the inspirational video of that :P.

**Comment by FlareFlo** [comment]
[1.2.1](https://github.com/Warthunder-Open-Source-Foundation/wt_custom_lang/releases/tag/v1.2.1) addresses this

**Comment by OshidaBCF** [comment]
yay
